[workspace]
resolver = "2"
members = [
    "crates/proto",
    "crates/core",
    "crates/crypto",
    "crates/net",
    "crates/store",
    "crates/daemon",
    "crates/cli",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false
license = "MIT"
repository = "https://github.com/firaslamouchi21/Ferry"
