// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditEventView = { id: string, actor: string, kind: string, item_id: string | null, occurred_at_millis: bigint, outcome: string, };
