// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DaemonStatus = { protocol_version: number, discovery_ok: boolean, transport_ok: boolean, store_ok: boolean, };
