// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "protocol_version_mismatch" | "peer_not_authorized" | "item_rejected_by_policy" | "illegal_state_transition" | "item_not_found" | "item_expired" | "hash_mismatch" | "frame_too_large" | "config_invalid" | "roster_invalid" | "internal";
