// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentityView = { fingerprint: string, signing_key_hex: string, sealing_key: string, display_name: string, listen_port: number, data_dir: string, protocol_version: number, auto_accept_from_roster: boolean, };
