// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { TransferState } from "./TransferState";

export type InboxItemView = { item_id: string, peer_id: string, origin_display_name: string, kind: ItemKind, name: string, state: TransferState, size_bytes: bigint, is_burn_after_read: boolean, hash_hex: string | null, received_at_millis: bigint | null, expires_at_millis: bigint | null, };
