// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcResource } from "./IpcResource";

export type IpcEvent = { "event": "changed", "params": { resource: IpcResource, id: string | null, } } | { "event": "progress", "params": { item_id: string, bytes: bigint, total: bigint, } };
