// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcRequest } from "./IpcRequest";
import type { RequestId } from "./RequestId";

export type IpcEnvelope = { ipc_protocol_version: number, request_id: RequestId, request: IpcRequest, };
