// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FerryError } from "./FerryError";
import type { IpcResult } from "./IpcResult";

export type IpcOutcome = { "outcome": "ok", value: IpcResult, } | { "outcome": "err", error: FerryError, };
