// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcOutcome } from "./IpcOutcome";
import type { RequestId } from "./RequestId";

export type IpcResponse = { request_id: RequestId, outcome: IpcOutcome, };
