// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEventView } from "./AuditEventView";
import type { DaemonStatus } from "./DaemonStatus";
import type { GistPublishedView } from "./GistPublishedView";
import type { IdentityView } from "./IdentityView";
import type { InboxItemView } from "./InboxItemView";
import type { MessageThreadView } from "./MessageThreadView";
import type { MessageView } from "./MessageView";
import type { PairBeginView } from "./PairBeginView";
import type { PairStatusView } from "./PairStatusView";
import type { ProviderAuthView } from "./ProviderAuthView";
import type { ProviderStatusView } from "./ProviderStatusView";
import type { RemoteJobStatusView } from "./RemoteJobStatusView";
import type { RemoteJobView } from "./RemoteJobView";
import type { RosterFetchPreviewView } from "./RosterFetchPreviewView";
import type { RosterImportSummaryView } from "./RosterImportSummaryView";
import type { RosterPeerView } from "./RosterPeerView";
import type { SealedImportView } from "./SealedImportView";
import type { SentItemView } from "./SentItemView";

export type IpcResult = { "result": "status", "value": DaemonStatus } | { "result": "ack" } | { "result": "roster_list", "value": Array<RosterPeerView> } | { "result": "roster_export", "value": { signed_roster_json: string, } } | { "result": "roster_import", "value": RosterImportSummaryView } | { "result": "send", "value": { item_id: string, } } | { "result": "inbox_list", "value": Array<InboxItemView> } | { "result": "open", "value": { content_base64: string, } } | { "result": "export_sealed", "value": { blob_base64: string, } } | { "result": "import_sealed", "value": SealedImportView } | { "result": "identity", "value": IdentityView } | { "result": "sent_list", "value": Array<SentItemView> } | { "result": "audit_list", "value": Array<AuditEventView> } | { "result": "pair_begin", "value": PairBeginView } | { "result": "pair_status", "value": PairStatusView } | { "result": "message_threads", "value": Array<MessageThreadView> } | { "result": "message_thread", "value": Array<MessageView> } | { "result": "provider_status", "value": ProviderStatusView } | { "result": "provider_auth", "value": ProviderAuthView } | { "result": "provider_auth_pending" } | { "result": "gist_published", "value": GistPublishedView } | { "result": "roster_fetch_preview", "value": RosterFetchPreviewView } | { "result": "remote_job", "value": RemoteJobView } | { "result": "remote_job_status", "value": RemoteJobStatusView };
