// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferState } from "./TransferState";

export type MessageView = { item_id: string, peer_id: string, outbound: boolean, body: string, state: TransferState, at_millis: bigint, };
