// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageThreadView = { peer_id: string, display_name: string, reachable: boolean, last_body: string, last_at_millis: bigint, count: number, };
