// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PairPhase } from "./PairPhase";

export type PairStatusView = { phase: PairPhase, phrase: string | null, peer_fingerprint: string | null, peer_display_name: string | null, error: string | null, };
