// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairBeginView = { pairing_id: string, listen_addr: string | null, code: string | null, };
