// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PairMode = { "role": "listen", "params": { display_name: string, } } | { "role": "connect", "params": { addr: string, code: string, display_name: string, } };
