// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderAuthView = { user_code: string, verification_uri: string, interval_secs: number, expires_in_secs: number, };
