// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderStatusView = { provider: string, connected: boolean, enabled: boolean, login: string | null, };
