// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteJobStatusView = { job_id: string, phase: string, result_url: string | null, result_summary: string | null, error: string | null, };
