// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RosterPeerView = { peer_id: string, display_name: string, paired_at_millis: bigint, fingerprint_short: string, reachable: boolean, last_seen_millis: bigint | null, };
