// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RosterPreviewEntryView } from "./RosterPreviewEntryView";

export type RosterFetchPreviewView = { signer_verifying_key_hex: string, known_signer: boolean, adds: number, already_present: number, entries: Array<RosterPreviewEntryView>, };
