// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RosterImportSummaryView = { signer_verifying_key_hex: string, peer_count: number, added: number, skipped_existing: number, };
