// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";

export type SealedImportView = { item_id: string, origin_peer_id: string, kind: ItemKind, name: string, size_bytes: bigint, };
