// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { TransferState } from "./TransferState";

export type SentItemView = { item_id: string, peer_id: string, peer_display_name: string, name: string, hash_hex: string, kind: ItemKind, state: TransferState, size_bytes: bigint, queued_at_millis: bigint | null, last_attempt_at_millis: bigint | null, last_error: string | null, };
